config/routes.rb
Rails.application.routes.draw do
  resources :listings

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  root :to => 'pages#index'

  resources :users, only: [:show]

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :listings do
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/setdate' => 'reservations#setdate'
  get '/duplicate' => 'reservations#duplicate'
  get '/reservations' => 'reservations#index'
  get '/reserved' => 'reservations#reserved'

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  #stripe connect oauth path
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'

  get '/not_checked' => 'listings#not_checked'

  get '/search' => 'pages#search'
  get '/ajaxsearch' => 'pages#ajaxsearch'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%Y年%m月%d日")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action :authenticate_user!
  before_action :set_conversation

  # redirect_to this action from conversation controller create action
  def index
    # check if this current_user are involved in conversation
    if current_user == @conversation.sender || current_user == @conversation.recipient
      @other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
      @messages = @conversation.messages.order("created_at DESC")
    else
      redirect_to conversations_path, alert: "他人のメッセージにアクセスできません"
    end

  end

  def create
    @message = @conversation.messages.new(message_params)
    @messages = @conversation.messages.order("created_at DESC")

    if @message.save
      #create.js.erb　が実行される
      respond_to do |format|
        format.js
      end
    end
  end

  private

  def set_conversation
    @conversation = Conversation.find(params[:conversation_id])
  end

  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/views/messages/_message.html.erb
<!-- patial just render single message -->
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-2 text-center row-space-1">
        <%= image_tag message.user.image, class: "img-circle profile-1" %>
        <br>
        <strong><%= message.user.name %></strong>
      </div>

      <div class="col-md-8">
        <%= message.body %>
      </div>

      <div class="col-md-2">
        <span class="pull-right"><%= message.message_time %></span>
      </div>
    </div>
  </div>
</div>

app/views/messages/create.js.erb
// 先頭に足す _message.html.erb to #chat
// messages/_message　をrender
// _message.html.erb内のmessageは@message
<% publish_to conversation_messages_path(@conversation) do %>
  $('#chat').prepend("<%= j(render @message)%>");
<% end %>
// メッセージの入力欄を空にする
$('#new_message')[0].reset();

app/views/messages/index.html.erb
<%= render 'partial/navbar' %>
<!-- this page has instance @other, @messages from message contr ,@conversation from convesation contrl-->
<div class="container">
  <div class="row">
    <div class="col-md-3 text-center">
      <%= image_tag @other.image, class: "img-circle profile-1" %><br>
      <strong><%= @other.name %></strong>
      <br>
      <%= link_to "Show Profile", @other, class: "btn btn-default btn-wide row-space-2 row-space-top-2" %>
    </div>

    <div class="col-md-9">

      <div class="panel panel-default">
        <div class="panel-heading">
          Conversation with <%= @other.name %>
        </div>
        <div class="panel-body">
          <%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
          <div class="form-group">
            <%= f.text_area :body, placeholder: "Write your messages here", class: "form-control" %>
          </div>

          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="actions">
            <%= f.submit "Send", class: "btn btn-danger pull-right" %>
          </div>
          <% end %>
        </div>
      </div>

      <div id="chat">
        <%= render @messages %>
      </div>
    </div>
  </div>
  <%= subscribe_to conversation_messages_path(@conversation)%>
</div>