config/routes.rb
Rails.application.routes.draw do
  resources :listings

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  root :to => 'pages#index'

  resources :users, only: [:show]

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :listings do
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/setdate' => 'reservations#setdate'
  get '/duplicate' => 'reservations#duplicate'
  get '/reservations' => 'reservations#index'
  get '/reserved' => 'reservations#reserved'

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  #stripe connect oauth path
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'

  get '/not_checked' => 'listings#not_checked'

  get '/search' => 'pages#search'
  get '/ajaxsearch' => 'pages#ajaxsearch'

end

app/views/partial/_deviseErrorMsg.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript" charset="utf-8">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>');
    <% end %>
  </script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-devise">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Brand</a>
    </div>

    <!-- Location Search Form -->
    <div class="navbar-form navbar-left form-group row-space-2">
      <%= text_field_tag :search, params[:search], placeholder: "どちらまで?", class: "form-control",id:"pac-input" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
        <!-- ログインしていない時 -->
        <li><%= link_to "シッターになる", new_listing_path %></li>
        <li><a href="#">利用の流れ</a></li>
        <li><%= link_to "アカウント作成", new_user_registration_path %></li>
        <li><%= link_to "ログイン", new_user_session_path %></li>
        <% else %>
        <!-- ログインしている時 -->
        <li>
          <%= link_to conversations_path do %>
          <i class="fa fa-envelope"></i> メッセージ
          <% end %>
        </li>
        <li><%= link_to "シッターになる", new_listing_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <% if current_user.provider.present? %>
            <!-- 認証ログインをしている時 -->
            <%= image_tag current_user.image, class:"img-circle profile-0" %>
            <%= current_user.name %>
            <% else %>
            <%= current_user.email.split("@")[0] %>
            <% end %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", user_path(current_user) %></li>
            <li><%= link_to "プロフィール編集",  edit_user_registration_path %></li>
            <li><%= link_to "リスティング管理",  listings_path %></li>
            <li><%= link_to "ペットを預ける",  reservations_path %></li>
            <li><%= link_to "シッター予定",  reserved_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partial/_verticalnavbar.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <label style="color: #fff;">他の項目を編集する</label>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if controller?("listings") && action?("basics") %> listing-checked" id = "nav-basics">
          <%= link_to "基本事項", manage_listing_basics_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("description") %>" id = "nav-description" >
          <%= link_to "リスティングの内容", manage_listing_description_path(@listing) %>
        </li>

        <li class="<%= 'active' if controller?("listings") && action?("address") %>" id = "nav-address">
          <%= link_to "住所情報", manage_listing_address_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("price") %>" id = "nav-price">
          <%= link_to "料金", manage_listing_price_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("photos") %>" id = "nav-photos">
          <%= link_to "写真", manage_listing_photos_path(@listing),data:{no_turbolink: true} %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("calendar") %>">
          <%= link_to "カレンダー", manage_listing_calendar_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("bankaccount") %>" id = "nav-bankaccount">
          <%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %>
        </li>
        <li class="<%= 'active' if controller?("listings") && action?("publish") %>" id = "nav-publish">
          <%= link_to "公開する", manage_listing_publish_path(@listing) %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

<script>
$(function(){

  // basicsが常に存在するので、値は5からスタート
  var notchecked = 5;

  // Modelに値が存在するならば、chekedクラスを追加して、not checked-- により、あたいをヘラす。
  <% if !@listing.listing_title.blank? && !@listing.listing_content.blank? %>
  $('#nav-description').attr('class', 'listing-checked');
  notchecked--;
  <%else%>
  $('#nav-description').attr('class', 'listing-notchecked');
  <% end %>

  <% if !@listing.address.blank? %>
  $('#nav-address').attr('class', 'listing-checked');
  notchecked--;
  <%else%>
  $('#nav-address').attr('class', 'listing-notchecked');
  <% end %>

  <% if !@listing.photos.blank? %>
  $('#nav-photos').attr('class', 'listing-checked');
  notchecked--;
  <%else%>
  $('#nav-photos').attr('class', 'listing-notchecked');
  <% end %>

  <% if !@listing.price_pernight.blank? %>
  $('#nav-price').attr('class', 'listing-checked');
  notchecked--;
  <%else%>
  $('#nav-price').attr('class', 'listing-notchecked');
  <% end %>

  <% if !@listing.user.stripe_user_id.blank? %>
  $('#nav-bankaccount').attr('class', 'listing-checked');
  notchecked--;
  <%else%>
  $('#nav-bankaccount').attr('class', 'listing-notchecked');
  <% end %>


  // notcheckedがあるなら、残り〜と表示して、違うなら、公開するを押せるようにする。
  if(notchecked > 0){
    $("li#nav-publish a").text("残り"+ notchecked +"ステップ");
    $("li#nav-publish a").removeAttr("href");
  }else{
    $("li#nav-publish a").text("公開する");
  }

  // ajaxでそのリスティングの、not_checkedランを更新する。
  $.ajax({
    // jsonで送った、notcheckedのデータでmodelのnot_checkedを更新する
    url: '/not_checked',
    // this data is data for sending to url
    data: {'listing_id': <%= @listing.id %>,'not_checked': notchecked},
    dataType: 'json'
  });
});
</script>