config/routes.rb
Rails.application.routes.draw do
  resources :listings

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => 'registrations' }
  root :to => 'pages#index'

  resources :users, only: [:show]

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list
    end
  end

  resources :listings do
    resources :reservations, only: [:new, :create]
  end

  resources :listings do
    resources :reviews, only: [:create, :destroy]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/setdate' => 'reservations#setdate'
  get '/duplicate' => 'reservations#duplicate'
  get '/reservations' => 'reservations#index'
  get '/reserved' => 'reservations#reserved'

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'

  #stripe connect oauth path
  get '/connect/oauth' => 'stripe#oauth', as: 'stripe_oauth'
  get '/connect/confirm' => 'stripe#confirm', as: 'stripe_confirm'
  get '/connect/deauthorize' => 'stripe#deauthorize', as: 'stripe_deauthorize'

  get '/not_checked' => 'listings#not_checked'

  get '/search' => 'pages#search'
  get '/ajaxsearch' => 'pages#ajaxsearch'

end

app/views/pages/_filter.html.erb
<!-- Search Form -->
<%= search_form_for @search, url: search_path do |f| %>


<div class="filter">

  <!-- カレンダー -->
  <div class="row filter-section">
    <div class="col-md-1 text-center col-md-offset-1">
      <h4>日付</h4>
    </div>
    <div class="col-md-4 col-xs-6 col-md-offset-1">
      <%= text_field_tag :start_date, params[:start_date], placeholder: "Start Date", class: "form-control",value: session[:start_date] %>
    </div>
    <div class="col-md-4 col-xs-6">
      <%= text_field_tag :end_date, params[:end_date], placeholder: "End Date", class: "form-control",value: session[:end_date] %>
    </div>
  </div>

  <hr>
  <!-- 価格 -->
  <div class="row filter-section">
    <div class="col-md-1 text-center col-md-offset-1">
      <h4>価格</h4>
    </div>

    <div class="col-md-4 col-xs-6 col-md-offset-1">
      <%= f.text_field :price_pernight_gteq, placeholder: "Min",value:session[:price_pernight_gteq],class:"form-control" %>
    </div>
    <div class="col-md-4 col-xs-6">
      <%= f.text_field :price_pernight_lteq, placeholder: "Max",value:session[:price_pernight_lteq],class:"form-control" %>
    </div>
  </div>

  <!-- 家の形態 -->
  <div class="row filter-section row-space-top-4 row-space-4">

    <div class="col-md-3 text-center">
      <h4>家のタイプ</h4>
    </div>

    <div class="col-md-3 col-xs-4">
      <%= check_box_tag "q[home_type_eq_any][]", "マンション",session[:Mansion] %> マンション
    </div>
    <div class="col-md-3 col-xs-4">
      <%= check_box_tag "q[home_type_eq_any][]", "一軒家",session[:House] %> 一軒家
    </div>
    <div class="col-md-3 col-xs-4">
      <%= check_box_tag "q[home_type_eq_any][]", "アパート",session[:Apartment]%> アパート
    </div>
  </div>

  <!-- ペットタイプ -->
  <div class="row filter-section">
    <div class="col-md-3 col-xs-6 text-center">
      <h4>ペットのタイプ</h4>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="form-group">
        <%= f.select :pet_type_eq, [["犬","犬"], ["猫","猫"], ["鳥類","鳥類"], ["爬虫類","爬虫類"], ["魚類","魚類"], ["両生類","両生類"], ["その他","その他"]], { :include_blank => "Select",:selected => session[:pet_type_eq]},{class: "form-control"} %>
      </div>
    </div>

    <div class="col-md-2 col-xs-6 text-center">
      <h4>飼育歴</h4>
    </div>
    <div class="col-md-3 col-xs-6">
      <div class="form-group">
        <%= f.select :breeding_years_gteq, [["1year",1], ["2",2], ["3",3], ["4",4], ["5",5], ["6",6]], {:include_blank => "Select",:selected => session[:breeding_years_gteq]}, {class: 'form-control'} %>
      </div>
    </div>

  </div>

  <%= hidden_field_tag :search, session[:address], :id => "search-address" %>

  <!-- Submitボタン -->
  <div class="row filter-section">
    <div class="col-md-3">
      <%= f.submit "Re-search", class: "btn btn-danger" %>
    </div>
  </div>
</div>
<% end %>



<!-- datepickerのスクリプト -->
<script>
$(function() {
  $("#start_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
      $('#end_date').attr('disabled', false);
    }
  });

  $("#end_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });
})
</script>

app/views/pages/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright &copy; Your Website 2014</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li><a href="#"><i class="fa fa-twitter"></i></a>
          </li>
          <li><a href="#"><i class="fa fa-facebook"></i></a>
          </li>
          <li><a href="mailto:自分のメールアドレス?subject=お問い合わせ"><i class="fa fa-envelope"></i></a>
          </li>
        </ul>
      </div>
      <div class="col-md-4">
        <ul class="list-inline quicklinks">
          <li class="text-white"><a href="#">Privacy Policy</a>
          </li>
          <li class="text-white"><a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/pages/_list.html.erb
<% if @arrlistings  %>
<div class="row filter-section">
  <% @arrlistings.each do |listing| %>
  <div class="col-md-6">
    <%= link_to listing do %>
    <div class="panel panel-default">
      <div class="panel-heading panel-listing text-center" style="padding: 0;">
        <%= link_to(listing) do %>
        <%= image_tag listing.photos[0].image.url(:medium)  if listing.photos.length > 0 %>
        <% end %>

        <div class="price-card">
          <%= listing.price_pernight %> 円
        </div>
      </div>


      <div class="panel-body">
        <div class="col-md-10 col-xs-10">
          <%= listing.listing_title %>
        </div>
        <div class="col-md-2 col-xs-2">
          <%= image_tag listing.user.image,class:"img-circle profile-1" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  <% end %>
</div>
<% end %>

app/views/pages/ajaxsearch.js.erb
$('#search-result').html("<%= j render 'pages/list' %>");
document.getElementById('search-address').value = "<%= session[:address] %>";

<% @arrlistings.each do |listing| %>
//markerはこの関数の中で同じ変数
var marker = new google.maps.Marker({
  position: new google.maps.LatLng(<%= listing.latitude %>, <%= listing.longitude %>),
  map: map
});

// マーカー配列にマーカを保存
markers.push(marker);

// マーカーがクリックされた時の処理
marker.addListener('click', function() {

  <% if !listing.photos.blank? %>
  var content = "<div>" + '<a href="/listings/' + <%= listing.id %> +'">' + "<img src="+"<%= listing.photos[0].image.url(:thumb) %>" + " " + "style='width: 100%;height: 150px;'" +"alt='139'>" + "</a>" + '<br>' + "<h5><%= listing.listing_title %></h5>" + "<div class="+"col-md-12"+">"+"<h4>Reviews <span class="+"average_rating_listing"+"></span>"+"(<%= listing.reviews.count %>)"+"</h4></div>";
  <% end %>

  // infowindowを作成
  var infowindow = new google.maps.InfoWindow({
    content: content,
    maxWidth: 280
  });

  infowindow.open(map, this);
  infowindows.push(infowindow);

  //infowindowが完全に読み込まれた時に実行される処理
  google.maps.event.addListener(infowindow, 'domready', function() {
    $('.average_rating_listing').raty({
      path: '/assets',
      readOnly: true,
      score: <%= listing.average_star_rate %>
    });
  });
});
<% end %>

app/views/pages/index.html.erb
<script type="text/javascript">
$(function(){
  $(".navbar").removeClass("navbar-devise");
  $(".navbar").addClass("navbar-default");
});
</script>

<div class="jumbotron">
  <%= render 'partial/navbar' %>

  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <h1 class="display-3">Hello, world!</h1>
      </div>
    </div>
  </div>

  <!-- Search Form -->
  <div class="top-search-field">
    <%= form_tag search_path, method: :get do %>
    <div class="row">
      <div class="container">
        <%= hidden_field_tag :lat %>
        <%= hidden_field_tag :lng %>
        <div class="col-md-7 col-xs-10" style="padding-right: 0px">
          <%= text_field_tag :search, params[:search], placeholder: "希望の場所はどこですか？", class: "form-control", id: "top-search-form" %>
        </div>

        <div class="col-md-2 hidden-xs hidden-sm">
          <%= text_field_tag :start_date, params[:start_date], placeholder: "チェックイン", class: "form-control" %>
        </div>
        <div class="col-md-2 hidden-xs hidden-sm">
          <%= text_field_tag :end_date, params[:end_date], placeholder: "チェックアウト", class: "form-control" %>
        </div>
        <div class="col-md-1 col-xs-2" style="padding-left: 0px; ">
          <%= submit_tag "検索", class: "btn btn-danger" %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

<div class="container">
  <!-- ご利用の流れ -->
  <section id="services">
    <div class="container">
      <div class="row row-space-4">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">ご利用の流れ</h2>
          <h3 class="section-subheading">Petshuggyはペットを預けるサービスです</h3>
        </div>
      </div>
      <div class="row text-center">
        <div class="col-md-4">
          <%= image_tag 'search-icon'%>
          <h4 class="service-heading">探す</h4>
          <p class="text-muted hidden-xs">まず、ペットを預けるペットシッターをこのサイトで検索しましょう。</p>
        </div>
        <div class="col-md-4">
          <%= image_tag 'calendar-icon'%>
          <h4 class="service-heading">予約する</h4>
          <p class="text-muted hidden-xs">いいなと思うペットシッターがいたら、ペットを預けたい日にちを予約しましょう。</p>
        </div>
        <div class="col-md-4">
          <%= image_tag 'home-icon'%>
          <h4 class="service-heading">預ける</h4>
          <p class="text-muted hidden-xs">予約した日の当日になったら、ペットを預けて、自分たちの時間を楽しみましょう！</p>
        </div>
      </div>
    </div>
  </section>

  <!--　おすすめのシッター -->
  <section id="portfolio" class="bg-light-gray row-space-top-4 row-space-4">
    <div class="container">
      <div class="row row-space-2">
        <div class="col-lg-12 text-center">
          <h3 class="section-heading">おすすめのシッター紹介</h3>
          <h4 class="section-subheading">Petshuggy認定のペットシッターです</h4>
        </div>
      </div>

      <div class="row">
        <% @users.each do |user|%>
        <% if !user.listings.blank?%>
        <div class="col-md-4 col-sm-6 portfolio-item row-space-2">
          <%= link_to listing_path(user.listings[0]) do %>
          <%= image_tag user.listings[0].photos[0].image.url(:medium) %>
          <% end %>
          <div class="portfolio-caption">
            <%= image_tag user.image,class:"img-circle profile-1"%>
            <span style="font-weight: bold;"><%= user.name %>さん</span>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </section>
</div>

<%= render 'pages/footer' %>

<!-- datepickerのスクリプト -->
<script>
$(function() {
  $("#start_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
      $('#end_date').attr('disabled', false);
    }
  });

  $("#end_date").datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });
})
</script>

<script>
function init() {

  var input = /** @type {!HTMLInputElement} */(
    document.getElementById('top-search-form'));

    var autocomplete = new google.maps.places.Autocomplete(input);

    autocomplete.addListener('place_changed', function() {

      var place = autocomplete.getPlace();
      var lat = place.geometry.location.lat();
      var lng = place.geometry.location.lng();

      document.getElementById('lat').value = lat;
      document.getElementById('lng').value = lng;

      if (!place.geometry) {
        window.alert("Autocomplete's returned place contains no geometry");
        return;
      }

    });
  }

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&signed_in=true&libraries=places&callback=init"
  async defer></script>

app/views/pages/search.html.erb
<%= render 'partial/navbar' %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <!-- Search Filter -->
      <div id="search-filter">
        <%= render 'filter' %>
      </div>
      <!-- Search Result -->
      <div id="search-result" class="row-space-top-4">
        <%= render 'list' %>
      </div>
    </div>

    <div class="col-md-6">
      <div id="map" style="height: 500px;">
      </div>
    </div>
  </div>
</div>

<script>
function initMap() {
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat:<%= @latitude %>, lng: <%= @longitude %>},
    zoom: 13
  });
  var input = /** @type {!HTMLInputElement} */(
    document.getElementById('pac-input'));

    var autocomplete = new google.maps.places.Autocomplete(input);
    autocomplete.bindTo('bounds', map);

    // マーカーとインフォウィンドウの配列を用意
    markers = [];
    infowindows = [];

    <% @arrlistings.each do |listing| %>

    //markerはこの関数の中で同じ変数
    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(<%= listing.latitude %>, <%= listing.longitude %>),
      map: map
    });

    // マーカー配列にマーカを保存
    markers.push(marker);

    // マーカーがクリックされた時の処理
    marker.addListener('click', function() {

      <% if !listing.photos.blank? %>
      var content = "<div>" + '<a href="/listings/' + <%= listing.id %> +'">' + "<img src="+"<%= listing.photos[0].image.url(:thumb) %>" + " " + "style='width: 100%;height: 150px;'" +"alt='139'>" + "</a>" + '<br>' + "<h5><%= listing.listing_title %></h5>" + "<div class="+"col-md-12"+">"+"<h4>Reviews <span class="+"average_rating_listing"+"></span>"+"(<%= listing.reviews.count %>)"+"</h4></div>";
      <% end %>

      // infowindowを作成
      var infowindow = new google.maps.InfoWindow({
        content: content,
        maxWidth: 280
      });

      infowindow.open(map, this);
      infowindows.push(infowindow);

      //infowindowが完全に読み込まれた時に実行される処理
      google.maps.event.addListener(infowindow, 'domready', function() {
        $('.average_rating_listing').raty({
          path: '/assets',
          readOnly: true,
          score: <%= listing.average_star_rate %>
        });
      });
    });

    <% end %>

    //autocompleteの検索欄が変更された時の処理
    autocomplete.addListener('place_changed', function() {

      // すべてのinfowindowを消す
      infowindows.forEach(function(infowindow) {
        infowindow.close();
      });
      infowindows = [];

      // すべてのmarkerを消す
      markers.forEach(function(marker) {
        marker.setVisible(false);
      });
      markers = [];

      var place = autocomplete.getPlace();
      if (!place.geometry) {
        window.alert("Autocomplete's returned place contains no geometry");
        return;
      }

      // If the place has a geometry, then present it on a map.
      if (place.geometry.viewport) {
        map.fitBounds(place.geometry.viewport);
        map.setZoom(13);
      } else {
        map.setCenter(place.geometry.location);
        map.setZoom(13);  // Why 17? Because it looks good.
      }

      // 入力欄の場所の緯度経度情報を取得
      var lat = place.geometry.location.lat();
      var lng = place.geometry.location.lng();

      // 緯度経度情報をまとめる
      var geolocation = [lat,lng];

      // 場所の住所
      var location = place.formatted_address;

      // autocompleteの入力欄が変更されたらurlも変更して履歴に残す
      url = "/search?utf8=✓&search="+place.formatted_address;

      window.history.pushState(null,null,url);

      $.ajax({
        url: '/ajaxsearch',
        // this data is data for sending to url
        data: {'geolocation': geolocation, 'location': location}
      });

    });

    //google map がドラッグされた時の処理
    google.maps.event.addListener(map, 'dragend', function() {
      // すべてのinfowindowを消す
      infowindows.forEach(function(infowindow) {
        infowindow.close();
      });
      infowindows = [];

      // すべてのmarkerを消す
      markers.forEach(function(marker) {
        marker.setVisible(false);
      });
      markers = [];

      var pos = map.getCenter();
      var lat = pos.lat();
      var lng = pos.lng();

      var geolocation = [lat,lng];

      $.ajax({
        url: '/ajaxsearch',
        // this data is data for sending to url
        data: {'geolocation': geolocation}
      });

    });


  }

  </script>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&signed_in=true&libraries=places&callback=initMap"
  async defer></script>